services:
    mysqldb:
        container_name: mysqlcontainer
        image: mysql:8.0
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - $HOME/database:/var/lib/mysql
        ports:
            - 3306:3306
        expose:
            - 3306
        networks:
            - apinetwork

    backend-applicaiton:
        container_name: securecapitacontainer
        build: .
        image: securecapita:v2
        restart: unless-stopped
        expose:
            - 80

        ports:
            - 80:80

networks:
    apinetwork:
        driver: bridge