server:
    port : 8081
spring:
    profiles:
        #active: @spring.profiles.active@
        active: dev
    mail:
        host: smtp.gmail.com
        port: 587
        username: bogdanovtimm@gmail.com
        password: rxuirozapnegszbz
        properties:
            mail:
                smtp:
                    writetimeout: 5000
                    connectiontimeout: 5000
                    timeout: 5000
                    auth: true
                    starttls:
                        enable: true
                        required: true
application:
    title: SecureCapita
    version: 1.0
  