server:
    port: 80
spring:
    profiles:
        active: dev
    mail:
        host: smtp.gmail.com
        port: 587
        username: bogdanovtimm@gmail.com
        # password: will be given as an argument at application start
        properties:
            mail:
                smtp:
                    writetimeout: 5000
                    connectiontimeout: 5000
                    timeout: 5000
                    auth: true
                    starttls:
                        enable: true
                        required: true
application:
    title: SecureCapita
    version: 1.0
  